import type { ApiRouteDefinition } from "./definitions";
const dispatch = ["DISPATCHER"] as const;
export const dispatchRoutes = {
  dispatchDay: {
    method: "GET",
    path: "/api/dispatch/days/:date",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { params: "dateParams", query: "dayQuery" },
    responses: { 200: "dayResponse" },
  },
  propose: {
    method: "POST",
    path: "/api/dispatch/days/:date/propose",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { params: "dateParams", query: "dayQuery", headers: "mutationHeaders", body: "proposeRequest" },
    responses: { 200: "proposeResponse", 409: "apiError" },
  },
  getDraft: {
    method: "GET",
    path: "/api/dispatch/days/:date/draft",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { params: "dateParams", query: "dayQuery" },
    responses: { 200: "draftResponse" },
  },
  saveDraft: {
    method: "PUT",
    path: "/api/dispatch/days/:date/draft",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { params: "dateParams", query: "dayQuery", headers: "mutationHeaders", body: "saveDraftRequest" },
    responses: { 200: "draftResponse", 409: "apiError", 422: "validationErrorResponse" },
  },
  validate: {
    method: "POST",
    path: "/api/dispatch/days/:date/validate",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { params: "dateParams", query: "dayQuery", headers: "mutationHeaders", body: "validateRequest" },
    responses: { 200: "validationResult", 422: "validationErrorResponse" },
  },
  publish: {
    method: "POST",
    path: "/api/dispatch/days/:date/publish",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { params: "dateParams", query: "dayQuery", headers: "mutationHeaders", body: "publishRequest" },
    responses: { 200: "publishResponse", 409: "apiError", 422: "validationErrorResponse" },
  },
  versions: {
    method: "GET",
    path: "/api/dispatch/days/:date/versions",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { params: "dateParams", query: "dayQuery" },
    responses: { 200: "versionsResponse" },
  },
  runs: {
    method: "GET",
    path: "/api/dispatch/runs",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { query: "dayQuery" },
    responses: { 200: "runsResponse" },
  },
  exceptions: {
    method: "GET",
    path: "/api/dispatch/exceptions",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { query: "dayQuery" },
    responses: { 200: "exceptionsResponse" },
  },
  resolveConflict: {
    method: "POST",
    path: "/api/dispatch/conflicts/:id/resolve",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { params: "idParams", headers: "mutationHeaders", body: "resolveConflictRequest" },
    responses: { 200: "ackResponse", 409: "apiError" },
  },
  resolveIssue: {
    method: "POST",
    path: "/api/dispatch/issues/:id/resolve",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { params: "idParams", headers: "mutationHeaders", body: "resolveIssueRequest" },
    responses: { 200: "ackResponse", 409: "apiError" },
  },
  getFleet: {
    method: "GET",
    path: "/api/dispatch/fleet",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { query: "dateQuery" },
    responses: { 200: "fleetResponse" },
  },
  updateFleet: {
    method: "PUT",
    path: "/api/dispatch/fleet",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { headers: "mutationHeaders", body: "updateFleetRequest" },
    responses: { 200: "fleetResponse" },
  },
  outlook: {
    method: "GET",
    path: "/api/dispatch/outlook",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { query: "outlookQuery" },
    responses: { 200: "outlookResponse" },
  },
  outletHistory: {
    method: "GET",
    path: "/api/dispatch/outlets/:id/history",
    roles: dispatch,
    access: "session",
    transport: "json",
    request: { params: "idParams", query: "listQuery" },
    responses: { 200: "orderHistoryResponse" },
  },
} as const satisfies Record<string, ApiRouteDefinition>;
