import type { ApiRouteDefinition } from "./definitions";
import { HUMAN_ROLES } from "../common";
import { MAX_BLOB_BYTES } from "../field";
const dispatch = ["DISPATCHER"] as const;
const field = ["LOADER", "DRIVER"] as const;
export const fieldSupportRoutes = {
  snapshot: {
    method: "GET",
    path: "/api/field/snapshot",
    roles: field,
    access: "session",
    transport: "json",
    request: { query: "dateQuery" },
    responses: { 200: "fieldSnapshot" },
  },
  syncEvents: {
    method: "POST",
    path: "/api/sync/events",
    roles: field,
    access: "session",
    transport: "json",
    request: { headers: "mutationHeaders", body: "syncEventsIngressRequest" },
    clientBody: "syncEventsRequest",
    bodyLimit: 1000000,
    responses: { 200: "syncEventsResponse", 413: "apiError" },
  },
  uploadBlob: {
    method: "PUT",
    path: "/api/sync/blobs/:id",
    roles: field,
    access: "session",
    transport: "binary",
    bodyLimit: MAX_BLOB_BYTES,
    request: { params: "idParams", headers: "blobHeaders", body: "blobBody" },
    responses: { 200: "blobResponse", 413: "apiError" },
  },
  /** Blob bytes for authorised readers: the depot's dispatcher, the outlet's store, the uploading user (ADR 0035). */
  blob: {
    method: "GET",
    path: "/api/blobs/:id",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "binary",
    request: { params: "idParams" },
    responses: { 200: "blobBody", 404: "apiError" },
  },
  heartbeat: {
    method: "POST",
    path: "/api/sync/heartbeat",
    roles: field,
    access: "session",
    transport: "json",
    request: { headers: "mutationHeaders", body: "heartbeatRequest" },
    responses: { 200: "heartbeatResponse" },
  },
  changes: {
    method: "GET",
    path: "/api/changes",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "json",
    request: { query: "changesQuery" },
    responses: { 200: "changesResponse" },
  },
  stream: {
    method: "GET",
    path: "/api/stream",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "sse",
    request: { query: "streamQuery" },
    responses: { 200: "streamHint" },
  },
  demoState: {
    method: "GET",
    path: "/api/demo/state",
    roles: dispatch,
    access: "demo",
    transport: "json",
    request: {},
    responses: { 200: "demoState" },
  },
  demoClock: {
    method: "POST",
    path: "/api/demo/clock",
    roles: dispatch,
    access: "demo",
    transport: "json",
    request: { headers: "mutationHeaders", body: "demoClockRequest" },
    responses: { 200: "demoState" },
  },
  demoReset: {
    method: "POST",
    path: "/api/demo/reset",
    roles: dispatch,
    access: "demo",
    transport: "json",
    request: { headers: "mutationHeaders", body: "demoResetRequest" },
    responses: { 200: "demoState" },
  },
  demoTick: {
    method: "POST",
    path: "/api/demo/tick",
    roles: dispatch,
    access: "demo",
    transport: "json",
    request: { headers: "mutationHeaders" },
    responses: { 200: "demoTickResponse" },
  },
  health: {
    method: "GET",
    path: "/api/healthz",
    roles: [],
    access: "public",
    transport: "json",
    request: {},
    responses: { 200: "healthResponse" },
  },
  ready: {
    method: "GET",
    path: "/api/readyz",
    roles: [],
    access: "public",
    transport: "json",
    request: {},
    responses: { 200: "readyResponse", 503: "notReadyResponse" },
  },
} as const satisfies Record<string, ApiRouteDefinition>;
