import type { ApiRouteDefinition } from "./definitions";
import { HUMAN_ROLES } from "../common";
const store = ["STORE"] as const;
const field = ["LOADER", "DRIVER"] as const;
export const webRoutes = {
  login: {
    method: "POST",
    path: "/api/auth/login",
    roles: HUMAN_ROLES,
    access: "public",
    transport: "json",
    request: { headers: "mutationHeaders", body: "loginRequest" },
    responses: { 200: "sessionResponse", 401: "apiError", 429: "apiError" },
  },
  logout: {
    method: "POST",
    path: "/api/auth/logout",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "json",
    request: { headers: "mutationHeaders" },
    responses: { 200: "ackResponse" },
  },
  me: {
    method: "GET",
    path: "/api/auth/me",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "json",
    request: {},
    responses: { 200: "sessionResponse" },
  },
  reauth: {
    method: "POST",
    path: "/api/auth/reauth",
    roles: field,
    access: "expired-session",
    transport: "json",
    request: { headers: "mutationHeaders", body: "reauthRequest" },
    responses: { 200: "sessionResponse", 401: "apiError", 429: "apiError" },
  },
  outlets: {
    method: "GET",
    path: "/api/ref/outlets",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "json",
    request: { query: "referenceQuery" },
    responses: { 200: "outletsResponse" },
  },
  vehicles: {
    method: "GET",
    path: "/api/ref/vehicles",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "json",
    request: { query: "referenceQuery" },
    responses: { 200: "vehiclesResponse" },
  },
  products: {
    method: "GET",
    path: "/api/ref/products",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "json",
    request: { query: "referenceQuery" },
    responses: { 200: "productsResponse" },
  },
  calendar: {
    method: "GET",
    path: "/api/ref/calendar",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "json",
    request: { query: "calendarQuery" },
    responses: { 200: "calendarResponse" },
  },
  reasons: {
    method: "GET",
    path: "/api/ref/reasons",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "json",
    request: {},
    responses: { 200: "reasonsResponse" },
  },
  storeCutoff: {
    method: "GET",
    path: "/api/store/cutoff",
    roles: store,
    access: "session",
    transport: "json",
    request: { query: "dateQuery" },
    responses: { 200: "cutoffResponse" },
  },
  storeDeliveries: {
    method: "GET",
    path: "/api/store/deliveries",
    roles: store,
    access: "session",
    transport: "json",
    request: { query: "dateQuery" },
    responses: { 200: "deliveriesResponse" },
  },
  createOrder: {
    method: "POST",
    path: "/api/store/orders",
    roles: store,
    access: "session",
    transport: "json",
    request: { headers: "orderCreateHeaders", body: "createOrderRequest" },
    responses: { 201: "order", 422: "apiError" },
  },
  storeOrders: {
    method: "GET",
    path: "/api/store/orders",
    roles: store,
    access: "session",
    transport: "json",
    request: { query: "orderListQuery" },
    responses: { 200: "ordersResponse" },
  },
  storeOrder: {
    method: "GET",
    path: "/api/store/orders/:id",
    roles: store,
    access: "session",
    transport: "json",
    request: { params: "idParams" },
    responses: { 200: "orderDetail", 404: "apiError" },
  },
  cancelOrder: {
    method: "POST",
    path: "/api/store/orders/:id/cancel",
    roles: store,
    access: "session",
    transport: "json",
    request: { params: "idParams", headers: "mutationHeaders", body: "cancelOrderRequest" },
    responses: { 200: "order", 409: "apiError" },
  },
  receipt: {
    method: "POST",
    path: "/api/store/orders/:id/receipt",
    roles: store,
    access: "session",
    transport: "json",
    request: { params: "idParams", headers: "mutationHeaders", body: "receiptRequest" },
    responses: { 200: "order", 422: "apiError" },
  },
  reportIssue: {
    method: "POST",
    path: "/api/store/orders/:id/issues",
    roles: store,
    access: "session",
    transport: "json",
    request: { params: "idParams", headers: "mutationHeaders", body: "reportIssueRequest" },
    responses: { 201: "issueCreatedResponse" },
  },
  storeNotifications: {
    method: "GET",
    path: "/api/store/notifications",
    roles: store,
    access: "session",
    transport: "json",
    request: { query: "notificationsQuery" },
    responses: { 200: "notificationsResponse" },
  },
  storeNotificationsRead: {
    method: "POST",
    path: "/api/store/notifications/read",
    roles: store,
    access: "session",
    transport: "json",
    request: { headers: "mutationHeaders", body: "readNotificationsRequest" },
    responses: { 200: "readNotificationsResponse" },
  },
  notifications: {
    method: "GET",
    path: "/api/notifications",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "json",
    request: { query: "notificationsQuery" },
    responses: { 200: "notificationsResponse" },
  },
  notificationsRead: {
    method: "POST",
    path: "/api/notifications/read",
    roles: HUMAN_ROLES,
    access: "session",
    transport: "json",
    request: { headers: "mutationHeaders", body: "readNotificationsRequest" },
    responses: { 200: "readNotificationsResponse" },
  },
} as const satisfies Record<string, ApiRouteDefinition>;
