import type { ClientEvent } from "./field";
import type { ApiSchemaName, ApiDtoInput } from "./schemas";
import { resourceFixtures as r, MOCK_ID, MOCK_ORDER_ID, MOCK_TIME, MOCK_DATE } from "./resource-fixtures";

const error = {
  code: "FORBIDDEN",
  message_key: "errors.forbidden",
  params: { scope: "outlet" },
  requestId: "mock-request-1",
} as const;
const violation = {
  code: "WEIGHT_CAP_EXCEEDED",
  severity: "HARD",
  tripRef: "T015",
  vehicleId: r.vehicle.id,
  orderIds: [MOCK_ORDER_ID],
  params: { limit: 5000000, actual: 5000001 },
  message_key: "validator.WEIGHT_CAP_EXCEEDED",
} satisfies ApiDtoInput<"violation">;
const validation = { ok: false, violations: [violation] };
const reasons = {
  deferral: [{ code: "TIME_BUDGET", message_key: "reasons.TIME_BUDGET" }],
  problems: [{ code: "VEHICLE_PROBLEM", message_key: "problems.VEHICLE_PROBLEM" }],
  loadShort: [{ code: "STOCK_SHORT", message_key: "loadShort.STOCK_SHORT" }],
  loadDamaged: [{ code: "CRUSHED", message_key: "loadDamaged.CRUSHED" }],
  stopOutcome: [{ code: "VEHICLE_BREAKDOWN", message_key: "stopOutcome.VEHICLE_BREAKDOWN" }],
} satisfies ApiDtoInput<"reasonsResponse">;
const clientEvent = {
  clientEventId: MOCK_ID,
  deviceId: MOCK_ID,
  deviceSeq: 0,
  schemaVersion: 2,
  subject: { orderId: MOCK_ORDER_ID },
  source: "FIELD",
  actor: { userId: "loader-1", role: "LOADER" },
  capturedAt: MOCK_TIME,
  type: "LOAD_CONFIRMED",
  payload: { lines: [{ lineId: "line-1", qtyLoaded: 2 }] },
} satisfies ClientEvent;
const snapshotConfig = { rules: r.rulesConfig, reasons, noSignalAfterMin: 10, lateGraceMin: 15 };
const run = {
  vehicle: r.vehicle,
  trips: [r.trip],
  stopsDone: 0,
  stopsTotal: 1,
  lastHeardAt: MOCK_TIME,
  lastSyncAt: MOCK_TIME,
  pendingCount: 0,
  lateRisk: false,
  state: "ON_TRACK",
} satisfies ApiDtoInput<"run">;
const conflict = {
  id: MOCK_ID,
  kind: "FACT_ON_CANCELLED_STOP",
  state: "OPEN",
  orderId: MOCK_ORDER_ID,
  tripId: MOCK_ID,
  heldEventId: MOCK_ID,
  openedAt: MOCK_TIME,
  resolvedAt: null,
  resolution: null,
  note: null,
} satisfies ApiDtoInput<"conflict">;
const fieldConflict = {
  conflictId: MOCK_ID,
  clientEventId: MOCK_ID,
  kind: "FACT_ON_REASSIGNED_STOP",
  openedAt: MOCK_TIME,
  state: "RESOLVED",
  resolution: "REJECT_FACT",
  note: "Mock resolution",
  resolvedAt: MOCK_TIME,
} satisfies ApiDtoInput<"fieldConflict">;
/** Historical field context for Driver R3; independent of the current run snapshot. */
export const fieldConflictContextFixture = {
  conflictId: MOCK_ID,
  clientEventId: MOCK_ID,
  kind: "FACT_ON_CANCELLED_STOP",
  openedAt: MOCK_TIME,
  state: "OPEN",
  context: {
    fact: {
      ...clientEvent,
      id: MOCK_ID,
      receivedAt: MOCK_TIME,
      disposition: "HELD",
      type: "POD_CAPTURED",
      actor: { userId: "mock-driver", role: "DRIVER" },
      subject: { orderId: MOCK_ORDER_ID, tripId: r.trip.id, vehicleId: r.vehicle.id },
      basedOnPlanVersion: 1,
      clockOffsetMs: 1200,
      payload: { receiverName: "Mock receiver", photoBlobRefs: [MOCK_ID], signatureBlobRef: MOCK_ID },
    },
    original: {
      planVersion: 1,
      tripId: r.trip.id,
      tripDisplayId: r.trip.displayId,
      vehicleId: r.vehicle.id,
      stop: r.trip.stops[0]!,
    },
    changes: [
      {
        kind: "DEFERRED",
        fromVersion: 1,
        toVersion: 2,
        at: MOCK_TIME,
        from: { tripId: r.trip.id, vehicleId: r.vehicle.id },
        to: null,
        reasonCode: "TIME_BUDGET",
        note: "Route shortened",
      },
    ],
  },
} satisfies ApiDtoInput<"fieldConflict">;
export const fieldReassignedConflictContextFixture = {
  ...fieldConflictContextFixture,
  kind: "FACT_ON_REASSIGNED_STOP",
  context: {
    ...fieldConflictContextFixture.context,
    changes: [
      {
        kind: "MOVED_VEHICLE",
        fromVersion: 1,
        toVersion: 2,
        at: MOCK_TIME,
        from: { tripId: r.trip.id, vehicleId: r.vehicle.id },
        to: { tripId: "018f1234-5678-7890-abcd-ef1234567893", vehicleId: "018f1234-5678-7890-abcd-ef1234567894" },
        reasonCode: null,
        note: null,
      },
    ],
  },
} satisfies ApiDtoInput<"fieldConflict">;
const issue = {
  id: MOCK_ID,
  orderId: MOCK_ORDER_ID,
  kind: "SHORT",
  openedAt: MOCK_TIME,
  resolvedAt: null,
  note: "Missing crate",
} satisfies ApiDtoInput<"issue">;
const availability = {
  vehicleId: r.vehicle.id,
  date: MOCK_DATE,
  status: "AVAILABLE",
  reason: "SERVICE",
  note: "Service completed",
} as const;
const notification = {
  id: MOCK_ID,
  kind: "plan_changed",
  titleKey: "notifications.plan_changed",
  params: { version: 1 },
  entityRef: { type: "trip", id: MOCK_ID },
  createdAt: MOCK_TIME,
  readAt: null,
  group: "PLANNING",
} satisfies ApiDtoInput<"notification">;
const sessionUser = {
  role: "STORE",
  id: "store-1",
  displayName: "Mock store manager",
  locale: "en",
  outletId: MOCK_ID,
} satisfies ApiDtoInput<"sessionUser">;
const feedItem = {
  seq: "9007199254740993",
  kind: "order_changed",
  entity: { type: "order", id: MOCK_ORDER_ID },
  version: 1,
  at: MOCK_TIME,
} satisfies ApiDtoInput<"feedItem">;
const planningContext = {
  vehicleFuel: [{ vehicleId: r.vehicle.id, usedOtherDaysThisWeekMl: 15000 }],
  outletService: [{ outletId: r.outlet.id, daysSinceLastServed: 2, deferredLastRun: false }],
  loadedOrders: [],
} satisfies ApiDtoInput<"planningContext">;

/** Synthetic, deterministic examples for web mocks. These are not seed/account truth. */
export const apiFixtures = {
  planningContext,
  ...r,
  apiError: error,
  violation,
  validationResult: validation,
  idParams: { id: MOCK_ID },
  orderLineParams: { id: r.order.id, lineId: r.orderLine.id },
  dateParams: { date: MOCK_DATE },
  dateQuery: { date: MOCK_DATE },
  listQuery: { limit: 20 },
  mutationHeaders: { "x-nextdrop-csrf": "mock-csrf-token" },
  orderCreateHeaders: { "x-nextdrop-csrf": "mock-csrf-token", "idempotency-key": "mock-create-1" },
  ackResponse: { ok: true, serverTime: MOCK_TIME },
  loginRequest: { role: "STORE", loginId: "OUT015", password: "mock-password" },
  sessionUser,
  sessionResponse: {
    user: sessionUser,
    expiresAt: "2026-10-03T17:00:00.000Z",
    serverTime: MOCK_TIME,
    csrfToken: "mock-csrf-token",
  },
  reauthRequest: { role: "LOADER", pin: "1234", deviceId: MOCK_ID },
  referenceQuery: { depot: "Peliyagoda" },
  calendarQuery: { from: MOCK_DATE, to: "2026-10-10" },
  outletsResponse: { items: [r.outlet] },
  vehiclesResponse: { items: [r.vehicle] },
  productsResponse: { items: [r.product] },
  calendarResponse: { items: [r.calendarDay] },
  reasonsResponse: reasons,
  cutoffResponse: {
    serverTime: MOCK_TIME,
    requestedDate: "2026-10-04",
    deliveryDate: "2026-10-04",
    cutoffAt: "2026-10-03T10:30:00.000Z",
    orderingOpen: true,
    guidanceKey: null,
  },
  deliveriesResponse: {
    items: [{ order: r.order, trip: r.trip, signal: "NO_SIGNAL", lastHeardAt: MOCK_TIME }],
    serverTime: MOCK_TIME,
  },
  createOrderRequest: { requestedDate: "2026-10-04", lines: [{ productId: MOCK_ID, qty: 2 }] },
  orderListQuery: { date: MOCK_DATE, status: "PLANNED", limit: 20 },
  ordersResponse: { items: [r.order], nextCursor: null },
  cancelOrderRequest: { reason: "Mock store request" },
  receiptRequest: { lines: [{ lineId: "line-1", qtyReceived: 2 }] },
  reportIssueRequest: { kind: "SHORT", lines: [{ lineId: "line-1", qty: 1 }], note: "Missing crate" },
  issueCreatedResponse: { issueId: MOCK_ID, order: r.order },
  orderHistoryResponse: { items: [r.order], total: 1, nextCursor: null },
  dayQuery: { depot: "Peliyagoda" },
  dayResponse: {
    planningContext,
    date: MOCK_DATE,
    depot: "Peliyagoda",
    state: "PUBLISHED",
    ordersClosedAt: "2026-10-02T10:30:00.000Z",
    currentVersion: 1,
    queue: [r.order],
    demandCapacity: r.allocationStats,
    serverTime: MOCK_TIME,
  },
  proposeRequest: { revision: 0 },
  proposeResponse: { draft: r.draft, stats: r.allocationStats, trace: ["Mock allocation"] },
  saveDraftRequest: { revision: 1, data: r.draftData },
  draftResponse: { draft: r.draft },
  validateRequest: { data: r.draftData },
  publishRequest: { revision: 1 },
  publishResponse: { plan: r.planVersion, serverTime: MOCK_TIME },
  validationErrorResponse: { ...error, code: "VALIDATION_FAILED", message_key: "errors.validation_failed", validation },
  versionsResponse: { items: [r.planVersion] },
  run,
  runsResponse: { items: [run], serverTime: MOCK_TIME },
  conflict,
  issue,
  exception: { type: "CONFLICT", conflict, evidence: [MOCK_ID] },
  exceptionsResponse: {
    items: [
      { type: "CONFLICT", conflict, evidence: [MOCK_ID] },
      { type: "ISSUE", issue, evidence: [] },
    ],
  },
  resolveConflictRequest: { resolution: "ACCEPT_FACT", note: "Mock resolution" },
  resolveIssueRequest: { resolution: "CREDIT", note: "Mock credit" },
  resolveShortRequest: { outcome: "SHIP_PARTIAL", note: "Mock dispatcher decision" },
  resolveShortResponse: {
    order: {
      ...r.order,
      status: "LOADED",
      lines: [{ ...r.orderLine, qtyLoaded: 1 }],
      flags: { short: [{ lineId: r.orderLine.id, qtyShort: 1, resolution: "SHIP_PARTIAL" }], damaged: [] },
    },
    backorder: null,
    serverTime: MOCK_TIME,
  },
  requestReversalRequest: { to: "DEFERRED" },
  requestReversalResponse: {
    order: { ...r.order, status: "LOADED", pendingReversal: { to: "DEFERRED", planVersion: 1 } },
    serverTime: MOCK_TIME,
  },
  fleetResponse: {
    date: MOCK_DATE,
    items: [
      {
        vehicle: r.vehicle,
        availability: {
          status: "AVAILABLE",
          reason: null,
          note: null,
          changedAt: null,
        },
      },
    ],
  },
  updateFleetRequest: { changes: [availability] },
  outlookQuery: { depot: "Peliyagoda", from: MOCK_DATE, weeks: 4 },
  outlookResponse: {
    items: [
      {
        isoYear: 2026,
        isoWeek: 40,
        brand: "Fresh",
        demandVolumeL: 12000,
        chilledVolumeL: 8000,
        capacityVolumeL: 10000,
        reeferCapacityVolumeL: 6000,
      },
    ],
    serverTime: MOCK_TIME,
  },
  clientEvent,
  syncEventsRequest: { deviceId: MOCK_ID, events: [clientEvent] },
  syncEventsIngressRequest: { deviceId: MOCK_ID, events: [clientEvent] },
  syncEventResult: { clientEventId: MOCK_ID, status: "ACCEPTED", serverEventId: MOCK_ID, receivedAt: MOCK_TIME },
  syncEventsResponse: {
    results: [{ clientEventId: MOCK_ID, status: "ACCEPTED", serverEventId: MOCK_ID, receivedAt: MOCK_TIME }],
    serverTime: MOCK_TIME,
    feedHead: "9007199254740993",
  },
  snapshotConfig,
  fieldSnapshot: {
    role: "LOADER",
    planVersion: 1,
    serverTime: MOCK_TIME,
    feedCursor: "9007199254740993",
    resetEpoch: 1,
    config: snapshotConfig,
    scope: { depot: "Peliyagoda", date: MOCK_DATE, trips: [r.trip], reversals: [] },
  },
  heartbeatRequest: {
    deviceId: MOCK_ID,
    appVersion: "1.0.0",
    pendingCount: 0,
    lastSyncAt: MOCK_TIME,
    lastKnownStop: null,
  },
  heartbeatResponse: { serverTime: MOCK_TIME, feedHead: "9007199254740993", resetEpoch: 1 },
  fieldConflictsRequest: { clientEventIds: [MOCK_ID] },
  fieldConflict: fieldConflict,
  fieldConflictsResponse: { items: [fieldConflict], serverTime: MOCK_TIME, feedHead: "9007199254740993" },
  blobHeaders: { "content-type": "image/jpeg", "x-nextdrop-csrf": "mock-csrf-token" },
  blobBody: new Uint8Array([255, 216, 255, 217]),
  blobResponse: { clientBlobId: MOCK_ID, mime: "image/jpeg", size: 4 },
  changesQuery: { after: "0", limit: 100 },
  feedItem,
  changesResponse: { items: [feedItem], head: "9007199254740993", resetEpoch: 1 },
  streamQuery: { after: "0" },
  streamHint: { head: "9007199254740993", resetEpoch: 1 },
  notification,
  notificationsQuery: { unreadOnly: "true", limit: 20 },
  notificationsResponse: { items: [notification], unreadCount: 1, nextCursor: null },
  readNotificationsRequest: { all: false, ids: [MOCK_ID] },
  readNotificationsResponse: { updatedCount: 1, readAt: MOCK_TIME },
  demoPreset: "before-cutoff",
  demoState: {
    enabled: true,
    serverTime: MOCK_TIME,
    clockOffsetMs: 0,
    preset: "before-cutoff",
    resetEpoch: 1,
    lastResetBy: "DISPATCHER",
    lastResetAt: MOCK_TIME,
  },
  demoClockRequest: { serverTime: MOCK_TIME },
  demoResetRequest: { preset: "plan-published" },
  demoTickResponse: { transitionsApplied: 1, serverTime: MOCK_TIME },
  healthResponse: { status: "ok" },
  readyResponse: { status: "ok", checks: { database: "ok" } },
  notReadyResponse: { status: "unavailable", checks: { database: "failed" } },
} satisfies { [K in ApiSchemaName]: ApiDtoInput<K> };
