// Generated by `pnpm seed:pick-fixtures` (apps/api/prisma/seed/pick-fixtures.ts) from data/reference/*.csv.
// Do not edit by hand: change the criteria in the picker and run it again. ADR 0008, ADR 0027, seed-and-demo.md §15.5.
// Seed, e2e tests and docs import the story fixtures from here.

/** Tue 29 Sep 2026, the story delivery day. */
export const STORY_DATE = "2026-09-29";

// Peliyagoda peak day: walkthrough steps 1 to 6 (store and dispatcher).
export const PEAK_DAY_DEPOT = "Peliyagoda";
export const PEAK_STORE_DISTRICT = "Colombo";
/** Dilini's outlet, Waypoint Fresh. Replaces the design placeholder `OUT015`. */
export const PEAK_STORE_OUTLET_ID = "OUT004";

// Kandy hill run: walkthrough steps 7 to 14 (loader, driver, no-signal card, delayed confirmation).
export const HILL_RUN_DEPOT = "Kandy";
/** The low-coverage hill district (Talawakele area). */
export const HILL_DISTRICT = "Nuwara Eliya";
/** Sampath's reefer truck. Replaces the design placeholder `VEH001`. */
export const WALKTHROUGH_VEHICLE_ID = "VEH039";
/** Sampath, the walkthrough driver. */
export const WALKTHROUGH_DRIVER_ID = "DRV039";
/**
 * The hill trip. Replaces the design placeholder `T001`; its display ID is assigned when the plan is proposed.
 * Stops are in delivery order.
 */
export const WALKTHROUGH_TRIP = {
  vehicleId: "VEH039",
  tripNo: 1,
  brand: "Fresh",
  district: "Nuwara Eliya",
  stopOutletIds: ["OUT105", "OUT108", "OUT104", "OUT106", "OUT107"],
} as const;
/** The store receiving the walkthrough delivery: stop 2, the first one delivered offline. */
export const HILL_STORE_OUTLET_ID = "OUT108";
/** The Kandy loader account. */
export const KANDY_LOADER_LOGIN_ID = "LDR002";
